"""
Contratos estruturais de importação.

Este módulo define, de forma **declarativa**, quais colunas
são esperadas em cada tipo de importação (por ex.: CSV / XLS gerados
pelas ferramentas da Cisco).

- Não contém nenhuma lógica de negócio (apenas dados estáticos).
- É usado por `import_validator.validate_import_columns` para
  checar se o arquivo enviado pelo usuário está aderente ao contrato.

Como estender:
--------------
Para adicionar um novo tipo de importação, basta incluir uma nova chave
em `IMPORT_SCHEMAS`:

    IMPORT_SCHEMAS["NomeDoImport"] = {
        "required": ["Coluna obrigatória 1", "Coluna obrigatória 2"],
        "optional": ["Coluna opcional 1", "Coluna opcional 2"],
    }

Onde:
- "required": lista de cabeçalhos que DEVEM existir no arquivo.
- "optional": lista de cabeçalhos que PODEM existir, mas não são obrigatórios.
"""

from typing import Dict, List


# ==========================================================
# SCHEMAS
# ==========================================================

IMPORT_SCHEMAS: Dict[str, Dict[str, List[str]]] = {
    "CiscoSubscriptionCCW": {
        "required": [
            "End Customer",
            "Offer Name",
            "Consumption Status",
            "Over Consumed TF Groups",
            "TF Groups",
            "True Forward Effective Date",
            "Next True Forward",
            "Subscription ID",
            "Status",
            "Start Date",
            "End Date",
            "Initial Term",
            "Renewal Date",
            "Currency",
            "Monthly Charge",
            "TF Overage",
            "Purchase Order Number",
            "WebOrderID",
            "Buying Program ID",
            "Site URL",
            "Customer Success Manager",
            "Sales Specialist",
            "Customer Success Manager Email",
            "Sales Specialist Email",
            "Primary Billing Contact Name",
            "Primary Billing Contact Email",
            "Service To Contact Name",
            "Service To Contact Email",
            "End Customer Contact Name",
            "End Customer Contact Email",
            "End Customer Contact Phone",
            "Order Submitted Date",
            "Smart Account Name",
            "Renewal Manager",
            "Renewal Manager Email",
            "Provisioning Status"
        ],
        "optional": [
        ],
    },
    "CiscoReady": {
        "required": [
            "Serial Number / PAK number",
            "Coverage",
            "Covered Line Status",
            "Business Entity",
            "Sub Business Entity",
            "Product Family",
            "Product ID",
            "Product Description",
            "Asset Type",
            "Product Type",
            "Buying Program",
            "Item Quantity",
            "Covered Line Start Date",
            "Covered Line End Date",
            "Contract Type",
            "Contract Number",
            "Contract Description",
            "Subscription ID",
            "End of Product Sale Date",
            "Last Renewal Date",
            "End of Software Maintenance Date",
            "End-of-Life Announcement Date",
            "End of Routine Failure Analysis Date",
            "End of Vulnerability/Security Support Date",
            "Last Date of Support",
            "LDOS FY",
            "LDOS FY-FQ",
            "Install Site CR GU Name",
            "Install Site CR Parent Party Name",
            "Install Site CR Party Name",
            "Best Partner BE GEO ID",
            "Product List Price $",
            "Default Service List Price $",
            "Default Service Level",
            "Existing Coverage Level List Price $",
            "Instance ID",
            "Parent Instance ID",
            "Product SO",
            "Product PO",
            "Service SO",
            "Service PO",
            "Web Order ID",
            "Auto-renewal flag",
            "Installed Base Status",
            "ATR Eligible",
            "Do Not Renew Reason",
            "Deal ID",
            "Major/Minor",
        ],
        "optional": [
            "Migration PID Flag",
            "Migration PID List",
            "Pending True Forward Effective Date",
            "Consumed Suite Value (%)",
            "Exceptional Growth Anniversary",
            "Exceptional Growth TF Eligible
        ],
    },
    "NTTOracle": {
        "required": [],
        "optional": [
            "CONTRACT_NUMBER",
            "CONTRACTS_DESC",
            "CUSTOMER",
            "CONTRACT_START_DATE",
            "CONTRACT_END_DATE",
            "ESTIMATED_AMOUNT",
            "CURRENCY_CODE",
            "ENTITLEMENT",
            "SERVICE_LINE_STATUS",
            "PRODUCT",
            "DESCRIPTION",
            "LINE_NUMBER",
            "SUB_LINE_NUMBER",
            "SUBLINE_START_DATE",
            "SUBLINE_END_DATE",
            "SERIAL_NUMBER",
            "PRODUCT_LINE_STATUS",
            "ADDRESS1",
            "ADDRESS2",
            "ADDRESS3",
            "CITY",
            "POSTAL_CODE",
            "STATE",
            "SALES_PERSON",
            "COUNTY",
            "COUNTRY",
            "EXTENDED_PRICE",
            "QUANTITY",
            "DATE_TERMINATED",
            "GROSS_PROFIT",
            "CUSTOMER_PO",
            "INSTANCE_ID",
            "INSTANCE_NUMBER",
            "PARTS_VENDOR",
            "PARTS_CONTRACT",
            "SHORT_DESCRIPTION",
            "ACC_RULE",
            "ORDER_NUMBER",
            "CONTRACT NUMBER",
            "START DATE",
            "END DATE",
            "LINE STATUS",
            "LINE",
            "SUB LINE",
            "SERIAL NUMBER",
            "SALES PERSON",
            "INSTANCE NUMBER",
            "PARTS VENDOR",
            "PARTS CONTRACT",
            "ID ORACLE",
            "VENDOR NAME",
            "STATUS RENEWAL",
            "QUOTE REF",
            "APOLLO LINE ID",
            "ASSET START DATE",
            "ASSET END DATE",
            "Asset Number",
            "PRODUCT LINE STATUS",
            "POSTAL CODE",
            "SERVICE LEVEL",
            "ORDER NUMBER",
            "cro_contract_number",
            "cro_contracts_desc",
            "cro_customer",
            "cro_contract_start_date",
            "cro_contract_end_date",
            "cro_contract_amount",
            "cro_currency_code",
            "cro_entitlement",
            "cro_service_line_status",
            "cro_product",
            "cro_description",
            "cro_line_number",
            "cro_sub_line_number",
            "cro_asset_start_date",
            "cro_asset_end_date",
            "cro_serial_number",
            "cro_product_line_status",
            "cro_address1",
            "cro_address2",
            "cro_address3",
            "cro_city",
            "cro_postal_code",
            "cro_state",
            "cro_sales_person",
            "cro_country",
            "cro_extended_price",
            "cro_quantity",
            "cro_date_terminated",
            "cro_gross_profit",
            "cro_customer_po",
            "cro_instance_number",
            "cro_parts_vendor",
            "cro_parts_contract",
            "cro_short_description",
            "cro_acc_rule",
            "cro_order_number",
        ],
    },
}
