/**
 * CiscoEAClientReport
 * Migration of cisco_enterprise_agreement_license_usage.py → React
 * Used inside the Client Overview "Cisco EA Usage" detail panel.
 *
 * Sections:
 *  1. Filters (Subscription, Suite, Status, Overconsume only)
 *  2. Summary KPIs (Total SKUs, Purchased, Generated, Overconsume, Overall %)
 *  3. Next True Forward (NTF) + Net Balance
 *  4. True Forward Risk Assessment (alert banners + table)
 *  5. Purchased vs Generated by Suite (grouped bar — Plotly)
 *  6. Net Balance per Suite (bar — Plotly)
 *  7. Top 15 Overconsumed SKUs (horizontal bar — Plotly)
 *  8. Detail table (all columns, sorted by Balance, paginated)
 */

import { useMemo, useRef, useState } from "react";
import Plot from "react-plotly.js";
import { AlertCircle, AlertTriangle, CheckCircle, BarChart3, TrendingDown, List, ChevronDown } from "lucide-react";

function SectionTitle({ icon, label }: { icon: React.ReactNode; label: string }) {
  return (
    <div className="flex items-center gap-1.5 mb-2">
      <span className="text-gray-500 dark:text-gray-400">{icon}</span>
      <p className="text-[10px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">{label}</p>
    </div>
  );
}

// ─── Types ─────────────────────────────────────────────────────────────────
export type EARow = Record<string, unknown>;

interface Props {
  rows: EARow[];
  isDark?: boolean;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

const n = (v: unknown) => Number(v ?? 0) || 0;
const fmtN = (v: number) => v.toLocaleString("en-US");
const fmtD = (v: unknown) => v ? String(v).slice(0, 10) : "—";
const pct = (gen: number, pur: number) => pur > 0 ? Math.round((Math.min(gen, pur) / pur) * 100 * 10) / 10 : 0;
const TODAY_STR = new Date().toISOString().slice(0, 10);

function daysTo(dateStr: unknown): number | null {
  if (!dateStr) return null;
  try {
    const d = new Date(String(dateStr).slice(0, 10));
    const today = new Date(TODAY_STR);
    return Math.floor((d.getTime() - today.getTime()) / 86400000);
  } catch { return null; }
}

function Bar({ value, max = 100 }: { value: number; max?: number }) {
  const pv = Math.min(Math.max(value, 0), max);
  const col = value > 100 ? "bg-red-500" : value >= 90 ? "bg-orange-400" : "bg-green-500";
  return (
    <div className="w-full h-1.5 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden">
      <div className={"h-full rounded-full " + col} style={{ width: (pv / max * 100) + "%" }} />
    </div>
  );
}

function KpiTile({ label, value, sub, cls = "" }: { label: string; value: string | number; sub?: string; cls?: string }) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-3 flex flex-col gap-1">
      <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">{label}</p>
      <p className={"text-xl font-bold leading-tight " + cls}>{value}</p>
      {sub && <p className="text-[10px] text-gray-400 dark:text-gray-500">{sub}</p>}
    </div>
  );
}

function MultiSelect({
  label,
  options,
  value,
  onChange,
}: {
  label: string;
  options: string[];
  value: string[];
  onChange: (next: string[]) => void;
}) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement | null>(null);

  const toggleOption = (option: string) => {
    onChange(value.includes(option) ? value.filter((item) => item !== option) : [...value, option]);
  };

  const summary = value.length === 0
    ? "All"
    : value.length === 1
      ? value[0]
      : `${value.length} selected`;

  return (
    <div
      ref={rootRef}
      className="relative min-w-[130px]"
      onBlur={(e) => {
        if (!rootRef.current?.contains(e.relatedTarget as Node | null)) {
          setOpen(false);
        }
      }}
    >
      <label className="text-[10px] text-gray-500 dark:text-gray-400 uppercase mb-1 block">{label}</label>
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        className="w-full min-h-[34px] flex items-center justify-between gap-2 text-xs px-2.5 py-1.5 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-500"
      >
        <span className="truncate text-left">{summary}</span>
        <ChevronDown size={14} className={"shrink-0 transition-transform " + (open ? "rotate-180" : "")} />
      </button>
      {open && (
        <div className="absolute left-0 top-full mt-1 z-20 w-full min-w-[220px] rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-lg">
          <div className="max-h-56 overflow-auto py-1">
            {options.length === 0 ? (
              <p className="px-3 py-2 text-xs text-gray-400 dark:text-gray-500">No options</p>
            ) : (
              options.map((option) => {
                const checked = value.includes(option);
                return (
                  <label
                    key={option}
                    className="flex items-center gap-2 px-3 py-2 text-xs text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={checked}
                      onChange={() => toggleOption(option)}
                      className="w-4 h-4 rounded accent-blue-600"
                    />
                    <span className="truncate">{option}</span>
                  </label>
                );
              })
            )}
          </div>
          <div className="flex items-center justify-between gap-2 border-t border-gray-100 dark:border-gray-700 px-3 py-2">
            <button
              type="button"
              onClick={() => onChange(options)}
              className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline"
            >
              Select all
            </button>
            <button
              type="button"
              onClick={() => onChange([])}
              className="text-[10px] text-red-500 hover:underline"
            >
              Clear
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

const PLT = { dark: { bg: "rgba(0,0,0,0)", font: "#9CA3AF", grid: "#374151" },
              light: { bg: "rgba(0,0,0,0)", font: "#4B5563", grid: "#E5E7EB" } };

// ─── Main Component ────────────────────────────────────────────────────────

export default function CiscoEAClientReport({ rows, isDark = false }: Props) {
  const [filterSub, setFilterSub] = useState<string[]>([]);
  const [filterSuite, setFilterSuite] = useState<string[]>([]);
  const [filterStatus, setFilterStatus] = useState<string[]>([]);
  const [overOnly, setOverOnly] = useState(false);
  const [tablePage, setTablePage] = useState(1);
  const TABLE_PS = 20;

  const plt = isDark ? PLT.dark : PLT.light;

  // ── Filter options ────────────────────────────────────────────────────────
  const subOpts = useMemo(() => [...new Set(rows.map(r => String(r.mcea_subscription ?? "")).filter(Boolean))].sort(), [rows]);
  const suiteOpts = useMemo(() => [...new Set(rows.map(r => String(r.mcea_suite_name ?? "")).filter(Boolean))].sort(), [rows]);
  const statusOpts = useMemo(() => [...new Set(rows.map(r => String(r.mcea_status ?? "")).filter(Boolean))].sort(), [rows]);

  // ── Filtered data ─────────────────────────────────────────────────────────
  const filtered = useMemo(() => {
    let d = rows;
    if (filterSub.length)    d = d.filter(r => filterSub.includes(String(r.mcea_subscription ?? "")));
    if (filterSuite.length)  d = d.filter(r => filterSuite.includes(String(r.mcea_suite_name ?? "")));
    if (filterStatus.length) d = d.filter(r => filterStatus.includes(String(r.mcea_status ?? "")));
    if (overOnly)            d = d.filter(r => n(r.mcea_overconsume) > 0);
    return d;
  }, [rows, filterSub, filterSuite, filterStatus, overOnly]);

  // ── Summary KPIs ─────────────────────────────────────────────────────────
  const summary = useMemo(() => {
    let purchased = 0, generated = 0, overconsume = 0, netBalance = 0;
    for (const r of filtered) {
      purchased   += n(r.mcea_total_purchased);
      generated   += n(r.mcea_generated);
      overconsume += n(r.mcea_overconsume);
      netBalance  += n(r.mcea_balance);
    }
    const overallPct = pct(generated, purchased);
    const skusOver = filtered.filter(r => n(r.mcea_balance) < 0).length;
    // NTF date
    let ntfDate: string | null = null;
    for (const r of rows) {
      const d = r.mcea_ntf_date ? String(r.mcea_ntf_date).slice(0, 10) : null;
      if (d && (!ntfDate || d > ntfDate)) ntfDate = d;
    }
    const daysNtf = ntfDate ? daysTo(ntfDate) : null;
    return { purchased, generated, overconsume, netBalance, overallPct, skusOver, ntfDate, daysNtf };
  }, [filtered, rows]);

  // ── True Forward Risk per Subscription ───────────────────────────────────
  const tfRisk = useMemo(() => {
    const bySub: Record<string, EARow[]> = {};
    for (const r of filtered) {
      const sub = String(r.mcea_subscription ?? "—");
      if (!bySub[sub]) bySub[sub] = [];
      bySub[sub].push(r);
    }
    return Object.entries(bySub).map(([sub, items]) => {
      let ntfDate: string | null = null;
      for (const r of items) { const d = r.mcea_ntf_date ? String(r.mcea_ntf_date).slice(0, 10) : null; if (d && (!ntfDate || d > ntfDate)) ntfDate = d; }
      const days = ntfDate ? daysTo(ntfDate) : null;
      const skusOver = items.filter(r => n(r.mcea_balance) < 0).length;
      const overVol  = items.reduce((s, r) => s + n(r.mcea_overconsume), 0);
      const nearN    = items.filter(r => { const p2 = n(r.mcea_total_purchased); return p2 > 0 && n(r.mcea_generated) / p2 >= 0.9; }).length;
      const risk = days === null ? "OK" : days < 0 ? "OVERDUE" : days <= 30 ? "CRITICAL" : days <= 90 ? "WARNING" : "OK";
      return { sub, ntfDate: ntfDate ?? "—", days, skusOver, overVol, nearN, risk };
    }).sort((a, b) => (a.days ?? 9999) - (b.days ?? 9999));
  }, [filtered]);

  const overdueTF  = tfRisk.filter(r => r.risk === "OVERDUE");
  const criticalTF = tfRisk.filter(r => (r.risk === "CRITICAL" || r.risk === "WARNING") && r.skusOver > 0);

  // ── Charts data ───────────────────────────────────────────────────────────
  const suiteAgg = useMemo(() => {
    const m: Record<string, { p: number; g: number }> = {};
    for (const r of filtered) {
      const s = String(r.mcea_suite_name ?? "Unknown");
      if (!m[s]) m[s] = { p: 0, g: 0 };
      m[s].p += n(r.mcea_total_purchased);
      m[s].g += n(r.mcea_generated);
    }
    return Object.entries(m).map(([suite, v]) => ({ suite, ...v })).sort((a, b) => b.p - a.p);
  }, [filtered]);

  const netBySuite = useMemo(() => {
    const m: Record<string, number> = {};
    for (const r of filtered) {
      const k = String(r.mcea_suite_name ?? "Unknown") + " / " + String(r.mcea_subscription ?? "");
      m[k] = (m[k] ?? 0) + n(r.mcea_balance);
    }
    return Object.entries(m).map(([key, nb]) => ({ key, nb })).sort((a, b) => a.nb - b.nb);
  }, [filtered]);

  const topOver = useMemo(() => {
    const m: Record<string, number> = {};
    for (const r of filtered) { if (n(r.mcea_overconsume) > 0) { const k = String(r.mcea_sku ?? "—"); m[k] = (m[k] ?? 0) + n(r.mcea_overconsume); } }
    return Object.entries(m).map(([sku, v]) => ({ sku, v })).sort((a, b) => b.v - a.v).slice(0, 15);
  }, [filtered]);

  // ── Detail table ──────────────────────────────────────────────────────────
  const tableRows = useMemo(() => [...filtered].sort((a, b) => n(a.mcea_balance) - n(b.mcea_balance)), [filtered]);
  const totalPages = Math.max(1, Math.ceil(tableRows.length / TABLE_PS));
  const safePage = Math.min(tablePage, totalPages);
  const paginated = tableRows.slice((safePage - 1) * TABLE_PS, safePage * TABLE_PS);

  // ── NTF class ─────────────────────────────────────────────────────────────
  const ntfCls = summary.daysNtf === null ? "" : summary.daysNtf < 0 ? "text-red-500 dark:text-red-400" : summary.daysNtf <= 30 ? "text-red-500 dark:text-red-400" : summary.daysNtf <= 90 ? "text-orange-500 dark:text-orange-400" : "text-green-600 dark:text-green-400";

  // ── Last update ───────────────────────────────────────────────────────────
  const lastUpdate = useMemo(() => {
    let max = "";
    for (const r of rows) { const d = r.mcea_update ? String(r.mcea_update).slice(0, 10) : ""; if (d > max) max = d; }
    return max || "—";
  }, [rows]);

  const selectCls = "text-xs px-2.5 py-1.5 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-1 focus:ring-blue-500";

  // ─── Render ───────────────────────────────────────────────────────────────
  return (
    <div className="space-y-5">
      <p className="text-[10px] text-gray-400 dark:text-gray-500">Last measurement: {lastUpdate}</p>

      {/* ── 1. Filters ────────────────────────────────────────────────── */}
      <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-gray-200 dark:border-gray-700 p-3">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400 mb-2">Filters</p>
        <div className="flex flex-wrap gap-3 items-end">
          <MultiSelect label="Subscription" options={subOpts} value={filterSub} onChange={setFilterSub} />
          <MultiSelect label="Suite" options={suiteOpts} value={filterSuite} onChange={setFilterSuite} />
          <div>
            <label className="text-[10px] text-gray-500 dark:text-gray-400 uppercase mb-1 block">Status</label>
            <select multiple value={filterStatus} onChange={e => setFilterStatus([...e.target.selectedOptions].map(o => o.value))}
              className={selectCls + " min-w-[120px] max-h-20"} size={Math.min(statusOpts.length, 3)}>
              {statusOpts.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <label className="flex items-center gap-2 cursor-pointer text-xs text-gray-600 dark:text-gray-400 mt-4">
            <input type="checkbox" checked={overOnly} onChange={e => setOverOnly(e.target.checked)} className="w-4 h-4 rounded accent-red-500" />
            Overconsume only
          </label>
          {(filterSub.length > 0 || filterSuite.length > 0 || filterStatus.length > 0 || overOnly) && (
            <button onClick={() => { setFilterSub([]); setFilterSuite([]); setFilterStatus([]); setOverOnly(false); }}
              className="text-xs text-red-500 hover:text-red-700 mt-4">✕ Clear</button>
          )}
        </div>
        {filtered.length !== rows.length && <p className="text-[10px] text-blue-500 dark:text-blue-400 mt-1">{filtered.length} of {rows.length} records shown</p>}
      </div>

      {/* ── 2. KPI Row 1 ──────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        <KpiTile label="Total SKUs" value={filtered.length} />
        <KpiTile label="Total Purchased" value={fmtN(Math.round(summary.purchased))} />
        <KpiTile label="Total Generated" value={fmtN(Math.round(summary.generated))}
          cls={summary.generated > summary.purchased ? "text-red-500 dark:text-red-400" : "text-green-600 dark:text-green-400"} />
        <KpiTile label="Overconsume" value={fmtN(Math.round(summary.overconsume))}
          cls={summary.overconsume > 0 ? "text-red-500 dark:text-red-400" : "text-green-600 dark:text-green-400"}
          sub={summary.skusOver > 0 ? `${summary.skusOver} SKUs over` : "none"} />
        <KpiTile label="Overall Usage" value={summary.overallPct + "%"}
          cls={summary.overallPct > 100 ? "text-red-500 dark:text-red-400" : summary.overallPct >= 90 ? "text-orange-500 dark:text-orange-400" : "text-green-600 dark:text-green-400"} />
      </div>

      {/* KPI Row 2 — Net Balance + NTF */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <KpiTile label="Net Balance" value={(summary.netBalance >= 0 ? "+" : "") + fmtN(Math.round(summary.netBalance))}
          cls={summary.netBalance < 0 ? "text-red-500 dark:text-red-400" : "text-green-600 dark:text-green-400"} />
        <KpiTile label="Suites Net Negative" value={netBySuite.filter(r => r.nb < 0).length}
          cls={netBySuite.filter(r => r.nb < 0).length > 0 ? "text-red-500 dark:text-red-400" : "text-green-600 dark:text-green-400"} />
        <KpiTile label="Suites Net Positive" value={netBySuite.filter(r => r.nb >= 0).length}
          cls="text-green-600 dark:text-green-400" />
        <KpiTile label="Next True Forward" value={summary.ntfDate ?? "—"} cls={ntfCls}
          sub={summary.daysNtf !== null ? (summary.daysNtf < 0 ? "OVERDUE" : `in ${summary.daysNtf}d`) : ""} />
      </div>

      {/* ── 3. Usage gauge bar ────────────────────────────────────────── */}
      <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-gray-200 dark:border-gray-700 p-3">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">Overall Consumption</span>
          <span className={"text-sm font-bold " + (summary.overallPct > 100 ? "text-red-500" : summary.overallPct >= 90 ? "text-orange-500" : "text-green-600")}>{summary.overallPct}%</span>
        </div>
        <div className="w-full h-3 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden">
          <div className={"h-full rounded-full transition-all " + (summary.overallPct > 100 ? "bg-red-500" : summary.overallPct >= 90 ? "bg-orange-400" : "bg-green-500")}
            style={{ width: Math.min(summary.overallPct, 100) + "%" }} />
        </div>
        <div className="flex justify-between mt-1 text-[10px] text-gray-400 dark:text-gray-500">
          <span>0%</span><span>50%</span><span>100%{summary.overallPct > 100 ? ` → ${summary.overallPct}%` : ""}</span>
        </div>
      </div>

      {/* ── 4. True Forward Risk Alert ────────────────────────────────── */}
      {overdueTF.length > 0 && (
        <div className="flex gap-2 p-3 rounded-xl border border-red-300 dark:border-red-700 bg-red-50 dark:bg-red-900/20">
          <AlertCircle size={18} className="text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-bold text-red-700 dark:text-red-300">True Forward OVERDUE</p>
            <p className="text-xs text-red-600 dark:text-red-400 mt-0.5">
              {overdueTF.length} subscription(s) passed the NTF date with{" "}
              {fmtN(overdueTF.reduce((s, r) => s + r.overVol, 0))} licenses in overconsume.
              Immediate action required.
            </p>
          </div>
        </div>
      )}
      {overdueTF.length === 0 && criticalTF.length > 0 && (
        <div className="flex gap-2 p-3 rounded-xl border border-orange-300 dark:border-orange-700 bg-orange-50 dark:bg-orange-900/20">
          <AlertTriangle size={18} className="text-orange-600 dark:text-orange-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-bold text-orange-700 dark:text-orange-300">True Forward at Risk</p>
            <p className="text-xs text-orange-600 dark:text-orange-400 mt-0.5">
              {criticalTF.length} subscription(s) have overconsume with NTF in{" "}
              {Math.min(...criticalTF.map(r => r.days ?? 999))} day(s).
            </p>
          </div>
        </div>
      )}
      {overdueTF.length === 0 && criticalTF.length === 0 && summary.overconsume === 0 && (
        <div className="flex gap-2 p-3 rounded-xl border border-green-300 dark:border-green-700 bg-green-50 dark:bg-green-900/20">
          <CheckCircle size={18} className="text-green-600 dark:text-green-400 flex-shrink-0 mt-0.5" />
          <p className="text-sm font-semibold text-green-700 dark:text-green-300">No True Forward risk detected. All within contracted limits.</p>
        </div>
      )}

      {/* TF Risk table */}
      {tfRisk.some(r => r.risk !== "OK" || r.skusOver > 0) && (
        <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700">
          <table className="w-full text-xs">
            <thead><tr className="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
              {["Subscription","NTF Date","Days","SKUs Over","Overconsume","Near ≥90%","Risk"].map(h => (
                <th key={h} className="px-3 py-2 text-left font-semibold text-gray-600 dark:text-gray-300 whitespace-nowrap">{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {tfRisk.map((r, i) => {
                const riskColor = r.risk === "OVERDUE" || r.risk === "CRITICAL" ? "text-red-600 dark:text-red-400 font-bold" : r.risk === "WARNING" ? "text-orange-500 dark:text-orange-400 font-bold" : "text-green-600 dark:text-green-400";
                return (
                  <tr key={i} className="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                    <td className="px-3 py-2 font-medium text-gray-700 dark:text-gray-300">{r.sub}</td>
                    <td className="px-3 py-2 text-gray-600 dark:text-gray-400 whitespace-nowrap">{r.ntfDate}</td>
                    <td className="px-3 py-2 text-gray-500 dark:text-gray-400">{r.days !== null ? r.days : "—"}</td>
                    <td className={"px-3 py-2 " + (r.skusOver > 0 ? "text-red-600 dark:text-red-400 font-bold" : "text-gray-500 dark:text-gray-400")}>{r.skusOver}</td>
                    <td className={"px-3 py-2 " + (r.overVol > 0 ? "text-red-600 dark:text-red-400" : "text-gray-500 dark:text-gray-400")}>{fmtN(r.overVol)}</td>
                    <td className={"px-3 py-2 " + (r.nearN > 0 ? "text-orange-500 dark:text-orange-400" : "text-gray-500 dark:text-gray-400")}>{r.nearN}</td>
                    <td className={"px-3 py-2 " + riskColor}>{r.risk}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* ── 5. Purchased vs Generated by Suite ───────────────────────── */}
      {suiteAgg.length > 0 && (
        <div>
          <SectionTitle icon={<BarChart3 size={12} />} label="Purchased vs Generated by Suite" />
          <Plot
            data={[
              { type: "bar", name: "Purchased", x: suiteAgg.map(r => r.suite), y: suiteAgg.map(r => r.p), marker: { color: "#1E88E5" }, text: suiteAgg.map(r => fmtN(Math.round(r.p))), textposition: "outside" },
              { type: "bar", name: "Generated", x: suiteAgg.map(r => r.suite), y: suiteAgg.map(r => r.g), marker: { color: "#66BB6A" }, text: suiteAgg.map(r => fmtN(Math.round(r.g))), textposition: "outside" },
            ]}
            layout={{ barmode: "group", bargap: 0.4, height: 280, margin: { t: 20, b: 70, l: 10, r: 10 }, paper_bgcolor: plt.bg, plot_bgcolor: plt.bg, font: { color: plt.font, size: 11 }, xaxis: { gridcolor: plt.grid, tickangle: -30 }, yaxis: { gridcolor: plt.grid }, legend: { orientation: "h", yanchor: "bottom", y: 1.02, xanchor: "right", x: 1 }, showlegend: true }}
            config={{ responsive: true, displayModeBar: false }}
            style={{ width: "100%" }}
            useResizeHandler
          />
        </div>
      )}

      {/* ── 6. Net Balance per Suite ──────────────────────────────────── */}
      {netBySuite.length > 0 && (
        <div>
          <SectionTitle icon={<TrendingDown size={12} className="rotate-180" />} label="Net Balance per Suite / Subscription" />
          <Plot
            data={[{
              type: "bar", x: netBySuite.map(r => r.nb), y: netBySuite.map(r => r.key), orientation: "h",
              marker: { color: netBySuite.map(r => r.nb < 0 ? "#EF5350" : "#66BB6A") },
              text: netBySuite.map(r => (r.nb >= 0 ? "+" : "") + fmtN(Math.round(r.nb))), textposition: "outside",
            }]}
            layout={{ height: Math.max(200, netBySuite.length * 30 + 60), margin: { t: 20, b: 40, l: 200, r: 80 }, paper_bgcolor: plt.bg, plot_bgcolor: plt.bg, font: { color: plt.font, size: 11 }, xaxis: { gridcolor: plt.grid, title: "Net Balance" }, yaxis: { gridcolor: plt.grid, autorange: "reversed" }, shapes: [{ type: "line", x0: 0, x1: 0, y0: 0, y1: 1, yref: "paper", line: { color: plt.font, width: 1, dash: "dash" } }] }}
            config={{ responsive: true, displayModeBar: false }}
            style={{ width: "100%" }}
            useResizeHandler
          />
        </div>
      )}

      {/* ── 7. Top 15 Overconsumed SKUs ──────────────────────────────── */}
      {topOver.length > 0 && (
        <div>
          <SectionTitle icon={<TrendingDown size={12} />} label="Top 15 Overconsumed SKUs" />
          <Plot
            data={[{
              type: "bar", orientation: "h", x: topOver.map(r => r.v), y: topOver.map(r => r.sku),
              marker: { color: topOver.map(r => r.v > 0 ? "#EF5350" : "#FFA726") },
              text: topOver.map(r => fmtN(Math.round(r.v))), textposition: "outside",
            }]}
            layout={{ height: Math.max(200, topOver.length * 28 + 60), margin: { t: 10, b: 40, l: 200, r: 80 }, paper_bgcolor: plt.bg, plot_bgcolor: plt.bg, font: { color: plt.font, size: 11 }, xaxis: { gridcolor: plt.grid }, yaxis: { gridcolor: plt.grid, autorange: "reversed" } }}
            config={{ responsive: true, displayModeBar: false }}
            style={{ width: "100%" }}
            useResizeHandler
          />
        </div>
      )}

      {/* ── 8. Detail Table ───────────────────────────────────────────── */}
      <div>
        <SectionTitle icon={<List size={12} />} label={`Detail — License Usage per SKU (${tableRows.length})`} />
        <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700">
          <table className="w-full text-xs">
            <thead><tr className="bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
              {["Suite","SKU","Subscription","Status","Start","End","Purchased","Generated","Balance","Overconsume","Usage %"].map(h => (
                <th key={h} className="px-3 py-2 text-left font-semibold text-gray-600 dark:text-gray-300 whitespace-nowrap">{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {paginated.map((r, i) => {
                const bal = n(r.mcea_balance);
                const pur = n(r.mcea_total_purchased);
                const gen = n(r.mcea_generated);
                const usagePct = pct(gen, pur);
                return (
                  <tr key={i} className={"border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50" + (bal < 0 ? " bg-red-50/30 dark:bg-red-900/10" : "")}>
                    <td className="px-3 py-2 font-medium text-gray-700 dark:text-gray-300 whitespace-nowrap">{String(r.mcea_suite_name ?? "—")}</td>
                    <td className="px-3 py-2 text-gray-600 dark:text-gray-400 whitespace-nowrap font-mono text-[10px]">{String(r.mcea_sku ?? "—")}</td>
                    <td className="px-3 py-2 text-gray-600 dark:text-gray-400 whitespace-nowrap">{String(r.mcea_subscription ?? "—")}</td>
                    <td className="px-3 py-2 text-gray-500 dark:text-gray-400 whitespace-nowrap">{String(r.mcea_status ?? "—")}</td>
                    <td className="px-3 py-2 text-gray-500 dark:text-gray-400 whitespace-nowrap">{fmtD(r.mcea_start_date)}</td>
                    <td className="px-3 py-2 text-gray-500 dark:text-gray-400 whitespace-nowrap">{fmtD(r.mcea_end_date)}</td>
                    <td className="px-3 py-2 text-right text-gray-600 dark:text-gray-400">{fmtN(Math.round(pur))}</td>
                    <td className="px-3 py-2 text-right text-gray-600 dark:text-gray-400">{fmtN(Math.round(gen))}</td>
                    <td className={"px-3 py-2 text-right font-semibold " + (bal < 0 ? "text-red-600 dark:text-red-400" : "text-green-600 dark:text-green-400")}>{(bal >= 0 ? "+" : "") + fmtN(Math.round(bal))}</td>
                    <td className={"px-3 py-2 text-right " + (n(r.mcea_overconsume) > 0 ? "text-red-600 dark:text-red-400 font-semibold" : "text-gray-500 dark:text-gray-400")}>{fmtN(Math.round(n(r.mcea_overconsume)))}</td>
                    <td className="px-3 py-2 min-w-[80px]">
                      <div className="flex items-center gap-1.5">
                        <span className={"text-[10px] font-semibold w-10 text-right " + (usagePct > 100 ? "text-red-500" : usagePct >= 90 ? "text-orange-500" : "text-green-600")}>{usagePct}%</span>
                        <Bar value={usagePct} max={130} />
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex items-center justify-between pt-2">
            <p className="text-xs text-gray-500 dark:text-gray-400">{(safePage - 1) * TABLE_PS + 1}–{Math.min(safePage * TABLE_PS, tableRows.length)} of {tableRows.length}</p>
            <div className="flex items-center gap-1">
              {["«","‹"].map((lbl, idx) => (
                <button key={lbl} onClick={() => setTablePage(idx === 0 ? 1 : Math.max(1, safePage - 1))} disabled={safePage === 1}
                  className="flex items-center justify-center w-7 h-7 text-xs rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-30 disabled:cursor-not-allowed">{lbl}</button>
              ))}
              {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                const pg = Math.max(1, Math.min(safePage - 2, totalPages - 4)) + i;
                return pg <= totalPages ? (
                  <button key={pg} onClick={() => setTablePage(pg)}
                    className={"flex items-center justify-center w-7 h-7 text-xs rounded-lg " + (pg === safePage ? "bg-blue-600 text-white" : "border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800")}>{pg}</button>
                ) : null;
              })}
              {["›","»"].map((lbl, idx) => (
                <button key={lbl} onClick={() => setTablePage(idx === 0 ? Math.min(totalPages, safePage + 1) : totalPages)} disabled={safePage >= totalPages}
                  className="flex items-center justify-center w-7 h-7 text-xs rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800 disabled:opacity-30 disabled:cursor-not-allowed">{lbl}</button>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
